<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.tailwindcss.com" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="h-screen overflow-hidden flex items-center justify-center" style="background: #edf2f7;">
    <!-- This is an example component 
    Instagram: ccornejo__ -->
<?php echo $this->tag->form("login/register"); ?>
<div class='grid grid-cols-12'>
        <div class="col-span-4 text-white font-sans font-bold bg-black min-h-screen pl-7">
            <div class="grid grid-rows-6 grid-flow-col min-h-screen items-center justify-items-start">
                <div class="row-span-4 row-start-2 text-4xl">
                    Sign In                    
                    <div class="pt-10 pr-20">                        
                        <label class="text-sm font-sans font-medium">
                            Email
                        </label>
                        <?php echo $this->tag->textField(['placeholder'=>"email",'class'=>"w-full bg-black py-3 px-12 border hover: border-gray-500 rounded shadow text-base font-sans" ,"email"]); ?>
                        <!-- <input 
                            type="text" 
                            name="username" 
                            placeholder="Write your username" 
                            class="w-full bg-black py-3 px-12 border hover: border-gray-500 rounded shadow text-base font-sans"/>                             -->
                    </div>
                    <div class="pt-2 pr-20">
                        <label class="text-sm font-sans font-medium">
                            Password
                        </label>
                        <?php echo $this->tag->textField(['placeholder'=>"password",'class'=>"w-full bg-black py-3 px-12 border hover: border-gray-500 rounded shadow text-base font-sans" ,"password"]); ?>
                        <!-- <input 
                            type="password" 
                            name="password" 
                            placeholder="Write your password" 
                            class=" w-full bg-black py-3 px-12 border hover: border-gray-500 rounded shadow text-base font-sans"/> -->
                        <!-- <a href="" class="text-sm font-sans font-medium text-gray-600 underline">
                            Forgot password?
                        </a> -->
                    </div>
                    <label class="text-sm font-sans font-medium"><input  type="checkbox" value="remember-me" name="remember" > Remember me</label>
                    <!-- Button -->
                    <div class="text-sm font-sans font-medium w-full pr-20 pt-14">
                    <?php echo $this->tag->submitButton(['type'=>"button",'class'=>"text-center w-full py-4 bg-blue-700 hover:bg-blue-400 rounded-md text-white","login"]); ?>
                        <!-- <button 
                            type="button"   
                            class="text-center w-full py-4 bg-blue-700 hover:bg-blue-400 rounded-md text-white">
                                SIGN IN
                        </button> -->
                   
                    </div>
                    <a href="signup" class="text-sm font-sans font-medium text-gray-400 underline">
                    Don´t have an account? Sign up
                </a>
                </div>
                <!-- Text -->
               
            </div>         
        </div>

        <!-- Second column image -->
        <div class="banner col-span-8 text-white font-sans font-bold">
            <!-- Aquí iría algún comentario -->
        </div>    
</div>
</form>



<style>
    .banner {
        background: url( 'https://s1.1zoom.me/b6058/448/Dogs_Svetlana_Shelemeteva_Hug_Little_girls_568770_1920x1080.jpg' );
        background-repeat: no-repeat;
        background-size: cover        
    }
</style>
</body>
</html>